# YAML is case sensitive
# use space not tab
apiVersion: apps/v1 # specify api to use for deployment
kind: Deployment #kind of service/object you want to create
metadata:
  name: nginx-deployment # name the deployment
spec: 
  selector:
    matchLabels: 
      app: nginx # look for this label/tag to match with k8 service

  # create a ReplicaSet with instances/pods
  replicas: 5
  template: 
    metadata: 
      labels:
        app: nginx 
    spec:
      containers: 
      - name: nginx
        image: corinnai/tech264-nginx-cat:v1 # the image you create to run the modified nginx in container 
        ports: 
        - containerPort: 80
        resources:
      limits:
        memory: "128Mi"  
        cpu: "500m"      
      requests:
        memory: "64Mi"   
        cpu: "250m"  