---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: default
spec:
  ports:
  - nodePort: 30001 #rance is 30000-32768
    port: 80
    targetPort: 80 
  selector:
    app: nginx # this label to match service to deployment
  type: NodePort
