---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-svc # updated service name to match the Node.js app
  namespace: default
spec:
  ports:
  - nodePort: 30002 # specify the NodePort within range 30000-32768
    port: 3000
    targetPort: 3000 # target port inside the container
  selector:
    app: sparta-test-app # updated label to match the app label in the deployment
  type: NodePort # expose the service via NodePort for external access
